# pyproject.toml

[tool.ruff]
# Same as Black.
line-length = 88
indent-width = 4
exclude = ["notebooks"]

# Assume Python 3.9
target-version = "py39"

[tool.ruff.lint]
# Enable Pyflakes, pycodestyle, and isort rules.
select = ["E", "F", "W", "I"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
